namespace api.Domain.Entities;

public abstract class Entity
{
    /// <summary>
    /// Primary key. Left at the default <c>0</c> until EF Core inserts the row —
    /// the Npgsql provider configures this as <c>GENERATED BY DEFAULT AS IDENTITY</c>
    /// by convention, so Postgres assigns the next value on insert and EF reads
    /// it back into this property.
    /// </summary>
    public int Id { get; protected set; }
}
