import type { Task } from '../_types';
import { uid } from '../_lib/uid';
import { isoDate, nextDueOn } from '../_lib/dates';

// Anchor demo tasks on today so the seeded board always looks current; DueOn
// is derived from StartsOn + cadence below, exactly as the real app does.
const iso = () => isoDate(new Date());

export const seed = (): Task[] => {
  const tasks: Task[] = [
  // DAILY
  {
    id: uid(),
    cadence: 'daily',
    title: 'Morning pages — 3 longhand',
    done: false,
    priority: 'high',
    startsOn: iso(),
    tags: ['focus'],
    streak: 14,
    assignee: null,
    notes: 'Stream-of-consciousness, no editing. Burn after if it helps.',
    subtasks: [
      { id: uid(), taskId: 0, title: 'Pen, journal on desk by 6:45a', done: true },
      { id: uid(), taskId: 0, title: 'Phone in drawer', done: false },
    ],
  },
  {
    id: uid(),
    cadence: 'daily',
    title: '20-min walk before 11a',
    done: true,
    priority: 'med',
    startsOn: iso(),
    tags: ['body'],
    streak: 6,
    assignee: null,
    notes: 'Without podcasts. Just notice things.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'daily',
    title: 'Inbox to zero (unread only)',
    done: false,
    priority: 'med',
    startsOn: iso(),
    tags: ['work'],
    streak: 3,
    assignee: null,
    notes: "Triage, don't reply. Archive aggressively.",
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'daily',
    title: 'Read 10 pages',
    done: false,
    priority: 'low',
    startsOn: iso(),
    tags: ['mind'],
    streak: 22,
    assignee: null,
    notes: 'Currently: Patrick Leigh Fermor, A Time of Gifts.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'daily',
    title: 'Daily standup notes',
    done: true,
    priority: 'med',
    startsOn: iso(),
    tags: ['work'],
    streak: 0,
    assignee: null,
    notes: 'Three lines: yesterday / today / blockers.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'daily',
    title: 'Hydration — 2L',
    done: false,
    priority: 'low',
    startsOn: iso(),
    tags: ['body'],
    streak: 41,
    assignee: null,
    notes: '',
    subtasks: [
      { id: uid(), taskId: 0, title: 'Bottle #1 by lunch', done: false },
      { id: uid(), taskId: 0, title: 'Bottle #2 by 5p', done: false },
    ],
  },

  // WEEKLY
  {
    id: uid(),
    cadence: 'weekly',
    title: 'Submit timesheet',
    done: false,
    priority: 'high',
    startsOn: iso(),
    tags: ['work'],
    streak: 11,
    assignee: null,
    notes: "Pull hours from calendar Mon/Wed. Don't trust memory on Friday.",
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'weekly',
    title: '1:1 with Maya',
    done: false,
    priority: 'med',
    startsOn: iso(),
    tags: ['work'],
    streak: 8,
    assignee: null,
    notes: 'Topics: Q3 hiring, design review cadence, onboarding doc.',
    subtasks: [
      { id: uid(), taskId: 0, title: 'Pre-read draft of hiring plan', done: true },
      { id: uid(), taskId: 0, title: 'Followups from last week', done: false },
    ],
  },
  {
    id: uid(),
    cadence: 'weekly',
    title: 'Plan next week — Fri block',
    done: false,
    priority: 'high',
    startsOn: iso(),
    tags: ['focus'],
    streak: 5,
    assignee: null,
    notes: "90 min, no calls. Review goals, queue Monday's deep-work block.",
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'weekly',
    title: 'Long run, 6mi+',
    done: true,
    priority: 'med',
    startsOn: iso(),
    tags: ['body'],
    streak: 4,
    assignee: null,
    notes: 'Easy pace. Negative split if it feels good.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'weekly',
    title: 'Grocery + meal prep',
    done: false,
    priority: 'low',
    startsOn: iso(),
    tags: ['home'],
    streak: 9,
    assignee: null,
    notes: 'Two lunches + one dinner. Sheet-pan whatever.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'weekly',
    title: 'Call mom',
    done: false,
    priority: 'med',
    startsOn: iso(),
    tags: ['home'],
    streak: 12,
    assignee: null,
    notes: '',
    subtasks: [],
  },

  // MONTHLY
  {
    id: uid(),
    cadence: 'monthly',
    title: 'Pay rent',
    done: true,
    priority: 'high',
    startsOn: iso(),
    tags: ['money'],
    streak: 36,
    assignee: null,
    notes: 'Set the reminder for the 28th of the prior month.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'monthly',
    title: 'Review subscriptions',
    done: false,
    priority: 'med',
    startsOn: iso(),
    tags: ['money'],
    streak: 4,
    assignee: null,
    notes: "Anything I didn't use last month — cancel.",
    subtasks: [
      { id: uid(), taskId: 0, title: 'Export statement', done: false },
      { id: uid(), taskId: 0, title: 'Flag candidates', done: false },
      { id: uid(), taskId: 0, title: 'Cancel + log savings', done: false },
    ],
  },
  {
    id: uid(),
    cadence: 'monthly',
    title: 'Backup laptop → SSD',
    done: false,
    priority: 'med',
    startsOn: iso(),
    tags: ['work'],
    streak: 7,
    assignee: null,
    notes: 'Time Machine + manual copy of /projects.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'monthly',
    title: 'Q-board review prep',
    done: false,
    priority: 'high',
    startsOn: iso(),
    tags: ['work'],
    streak: 2,
    assignee: null,
    notes: "Slide 1: metrics. Slide 2: bets. Slide 3: asks. That's it.",
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'monthly',
    title: 'Budget reconciliation',
    done: false,
    priority: 'med',
    startsOn: iso(),
    tags: ['money'],
    streak: 11,
    assignee: null,
    notes: 'Categorize, compare to envelope, adjust.',
    subtasks: [],
  },

  // QUARTERLY
  {
    id: uid(),
    cadence: 'quarterly',
    title: 'OKR retrospective + next-Q plan',
    done: false,
    priority: 'high',
    startsOn: iso(),
    tags: ['work', 'focus'],
    streak: 6,
    assignee: null,
    notes:
      'Honest scoring. Then 3 objectives max for next quarter. Anything more is a wishlist.',
    subtasks: [
      { id: uid(), taskId: 0, title: "Score this quarter's KRs", done: true },
      { id: uid(), taskId: 0, title: 'Draft next-Q objectives', done: false },
      { id: uid(), taskId: 0, title: 'Share for review', done: false },
    ],
  },
  {
    id: uid(),
    cadence: 'quarterly',
    title: 'Therapist follow-up',
    done: false,
    priority: 'med',
    startsOn: iso(),
    tags: ['mind'],
    streak: 4,
    assignee: null,
    notes: '',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'quarterly',
    title: 'Renew domain + cert audit',
    done: true,
    priority: 'high',
    startsOn: iso(),
    tags: ['work'],
    streak: 8,
    assignee: null,
    notes: 'List all TLS certs, expirations, autorenew status.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'quarterly',
    title: 'Tax checkpoint',
    done: false,
    priority: 'med',
    startsOn: iso(),
    tags: ['money'],
    streak: 5,
    assignee: null,
    notes: 'Estimated payments + receipts folder hygiene.',
    subtasks: [],
  },
  {
    id: uid(),
    cadence: 'quarterly',
    title: 'Closet purge',
    done: false,
    priority: 'low',
    startsOn: iso(),
    tags: ['home'],
    streak: 3,
    assignee: null,
    notes: "If you haven't worn it this season and last, it goes.",
    subtasks: [],
  },
  ];
  return tasks.map((t) => ({ ...t, dueOn: nextDueOn(t.startsOn, t.cadence) }));
};
